Finished Project.
KelynPNjeri/Apple-Homepage-Clone pull request #1
Opened 2020-05-22 23:03 UTC by KelynPNjeri

This PR contains the full Apple Homepage as shown on the Odin Project.

2020-05-23 15:23 UTC, lucasmazo32 requested changes
# Changes required :wrench:

You are doing a great job so far, and the project is looking good. 

For the project to get approved, kindly implement the changes mentioned below.

### Happy coding! :computer:

## Lucas Mazo

2020-05-23 15:23 UTC, lucasmazo32 commented on .stickler.yml
> +# add the linters you want stickler to use for this project
- [ ] Kindly fix the lintern errors.

2020-05-23 15:23 UTC, lucasmazo32 commented on index.html
> +                <li class="nav-item">Support</li>
- [ ] These items should be links. Kindly fix that.

2020-05-23 15:23 UTC, lucasmazo32 commented on index.html
> +        <img src="./assets/images/promo_supplier_responsibility.jpg" alt="Promo Responsibility.">
- [ ] These images should be links. Kindly fix that.

2020-05-23 16:16 UTC, KelynPNjeri commented
I implemented all the changes requested in the project. I hope it meets the rubric.

2020-05-23 17:00 UTC, rammazzoti2000 requested changes
### Hello @KelynPNjeri awesome job on this project :tada: :rocket: 
You did great on this job, also implementing the cahnges required by the previousTSE.
There are still just some tiny issues to fix before this project can be approved, follow the comments bellow :point_down: 
### :stop_sign: Required changes :construction: :construction_worker: 
- [x] The search input can be improved so it looks better, see the inline comment please
- [x] The promo-cards have some space gap between them, change the width to 100% to fix the issue, see the inline comment.
### <em>Kindly fix the REQUIRED issues and send another code review request.

Cheers and Happy coding! :clap: 

Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of alexandru if you have any additional question)</em>
### :stop_sign: Status: Required Changes

2020-05-25 11:46 UTC, santiago-rodrig commented
# Pull Request under review by @santiago-rodrig (TSE)

2020-05-25 12:08 UTC, santiago-dev96 requested changes
# Changes required :no_entry_sign:
This project is **almost finished**, but I have to make sure that you are following instructions; because of this I must ask you to do the implement the suggestion I gave to the file `index.html`.

<img width="565" alt="Screen Shot 2020-05-25 at 8 06 42 AM" src="https://user-images.githubusercontent.com/43162770/82811422-b6d8d700-9e5e-11ea-9ca9-3beb8fe8d3d1.png">

Notice that the Apple logo is not a link, and that is a requirement.

You can find me in slack as **srodrig**, have a nice day! :wave:

2020-05-25 20:07 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-05-25 20:13 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon: 

Hi @KelynPNjeri, congratulations on fixing all the required changes pointed out by the previous TSE's :+1: Our project now meets all the minimum requirements to get approved :slightly_smiling_face: 

You can go ahead and merge to master and submit the project completion form :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-05-25 20:14 UTC, merged